
services: 
  web:
    build: .
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
 #ADDING DB
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fastapi_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_db

volumes:
  postgres_data:
